import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SidebarMenu from "@/components/SidebarMenu";
import StyleSwitcher from "@/components/StyleSwitcher";
import UserSidebar from "@/components/UserSidebar";
import ChatLeftSidebar from "@/components/chatleftsidebar";
import { Provider } from "./provider";
import UserChat from "@/components/UserChat";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body className="lg:flex">
        <Provider>
          <SidebarMenu />
          <StyleSwitcher />
          <ChatLeftSidebar />
          <UserChat />
          {children}
        </Provider>
      </body>
    </html>
  );
}
